assignment2/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('rst2slides.urls'))
]

rst2slides/urls.py
from django.conf.urls import url
from . import views

app_name = 'rst2slides'
urlpatterns = [
    url(r'^$',views.home_page,name =  'home_page'),
    url(r'^rst2html/$',views.rst2html, name = 'rst2html'),
    url(r'^uploadImagePage/$', views.uploadImagePage, name='uploadImagePage'),
    url(r'^uploadImage/$', views.uploadImage, name='uploadImage'),
    url(r'^imageCodeRst/$', views.imageCodeRst, name='imageCodeRst'),
    url(r'^loginPage/$', views.loginPage, name='loginPage'),
    url(r'^registerUser/$', views.registerUser, name='registerUser'),
    url(r'^loginUser/$', views.loginUser, name='loginUser'),
    url(r'^presentationPage/$', views.presentationPage, name='presentationPage'),
    url(r'^contactPage/$', views.contactPage, name='contactPage'),
    url(r'^logoutUser/$', views.logoutUser, name='logoutUser'),
    url(r'^(?P<slide_username>[a-zA-Z0-9_]*)/(?P<slide_name>[a-zA-Z0-9_]*)/editSlide/$', views.editSlide, name='editSlide'),
    url(r'^(?P<slide_username>[a-zA-Z0-9_]*)/(?P<slide_name>[a-zA-Z0-9_]*)/watchSlide/$', views.watchSlide, name='watchSlide'),
    url(r'^userSlide/$', views.userSlide, name='userSlide'),
    url(r'^deleteSlide/$', views.deleteSlide, name='deleteSlide'),
]

rst2slides/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Slide(models.Model):
    slide_name = models.CharField(max_length = 200)
    slide_username = models.CharField(max_length=200)
    slide_rst = models.TextField()
    slide_share_time = models.DateTimeField('date published')
    slide_last_update = models.DateTimeField('date last updated')
    slide_rating = models.IntegerField(default=0)
    slide_html_content = models.TextField(default="")
    slide_theme = models.CharField(max_length=200)
    slide_is_public = models.BooleanField(default=False)
    def __str__(self):
        return self.slide_name

rst2slides/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect, get_object_or_404
from django.core.files.storage import default_storage
import os
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from rst2slides.models import Slide
from django.contrib.auth import authenticate, login, logout
from django.utils import timezone


# Create your views here.
def home_page(request):
    request.session['loginPage'] = ""
    request.session['loginPageSuccess'] = ""
    request.session['editSlide'] = ""
    return render(request, 'rst2slides/home_page.html')


def rst2html(request):
    submit = request.GET['submit']
    user = request.user
    theme = request.GET['theme']  # keep name of theme
    slide_name = request.GET['slide_name']
    if '_' in slide_name:
        request.session['home_page'] = "Slide name must not have _"
        return HttpResponseRedirect(reverse('rst2slides:home_page'))
    else:
        slide_name = slide_name.replace(" ","_")  # keep name of slide and change space between character to _

    if submit == 'submit':
        textFile = open('rst2slides/static/rst2slides/{}.rst'.format(slide_name), 'w')
        textFile.write(request.GET['myTextBox'])
        textFile.close()

        if theme == 'deck':
            os.system(
                'rst2html5 --deck-js --pretty-print-code --embed-content rst2slides/static/rst2slides/{}.rst > rst2slides/templates/rst2slides/{}.html'.format(
                    slide_name,
                    slide_name))  # convert rst to html

        elif theme == 'clean':
            os.system(
                'rst2html5 rst2slides/static/rst2slides/{}.rst > rst2slides/templates/rst2slides/{}.html'.format(
                    slide_name,
                    slide_name))  # convert rst to html

        elif theme == 'reveal':
            os.system(
                'rst2html5 --jquery --reveal-js --pretty-print-code rst2slides/static/rst2slides/{}.rst > rst2slides/templates/rst2slides/{}.html'.format(
                    slide_name,
                    slide_name))  # convert rst to html


        elif theme == 'bootstrap':
            os.system(
                'rst2html5 --bootstrap-css --pretty-print-code --jquery --embed-content rst2slides/static/rst2slides/{}.rst > rst2slides/templates/rst2slides/{}.html'.format(
                    slide_name,
                    slide_name))  # convert rst to html

        htmlFile = open('rst2slides/templates/rst2slides/{}.html'.format(slide_name), 'r')
        html_content = ""
        for item in htmlFile:
            html_content = html_content + item  # keep all string in html file
        htmlFile.close()
        os.remove('rst2slides/static/rst2slides/{}.rst'.format(slide_name))  # remove rst file
        os.remove('rst2slides/templates/rst2slides/{}.html'.format(slide_name))  # remove html file
        return HttpResponse(html_content)
    else:

        textFile = open('rst2slides/static/rst2slides/{}.rst'.format(user.username), 'w')
        textFile.write(request.GET['myTextBox'])
        textFile.close()

        if theme == 'deck':
            os.system(
                'rst2html5 --deck-js --pretty-print-code --embed-content rst2slides/static/rst2slides/{}.rst > rst2slides/templates/rst2slides/{}.html'.format(
                    user.username,
                    user.username,
                    ))  # convert rst to html

        elif theme == 'clean':
            os.system(
                'rst2html5 rst2slides/static/rst2slides/{}.rst > rst2slides/templates/rst2slides/{}.html'.format(
                    user.username,
                    user.username,
                    ))  # convert rst to html

        elif theme == 'reveal':
            os.system(
                'rst2html5 --jquery --reveal-js --pretty-print-code rst2slides/static/rst2slides/{}.rst > rst2slides/templates/rst2slides/{}.html'.format(
                    user.username,
                    user.username,
                    ))  # convert rst to html

        elif theme == 'bootstrap':
            os.system(
                'rst2html5 --bootstrap-css --pretty-print-code --jquery --embed-content rst2slides/static/rst2slides/{}.rst > rst2slides/templates/rst2slides/{}.html'.format(
                    user.username,
                    user.username,
                    ))  # convert rst to html

        htmlFile = open('rst2slides/templates/rst2slides/{}.html'.format(user.username), 'r')
        html_content = ""
        for item in htmlFile:
            html_content = html_content + item  # keep all string in html file
        htmlFile.close()
        os.remove('rst2slides/static/rst2slides/{}.rst'.format(user.username))  # remove rst file
        os.remove(
            'rst2slides/templates/rst2slides/{}.html'.format(user.username))  # remove html file

        if submit == 'save':
            list_slide = Slide.objects.filter(
                slide_username=user.username)  # current user can't create slide is have same name already but another user can create same name
            slide_name = request.GET['slide_name']

            if not list_slide:
                slide = Slide(slide_name=slide_name, slide_username=user.username, slide_rst=request.GET['myTextBox'],
                              slide_share_time=timezone.now(), slide_last_update=timezone.now(), slide_rating=0,
                              slide_html_content=html_content, slide_theme=theme)
                slide.save()
                return HttpResponseRedirect(reverse('rst2slides:userSlide'))
            else:
                for slide in list_slide:
                    if slide_name == slide.slide_name:
                        if (theme == slide.slide_theme) and (request.GET['myTextBox'] == slide.slide_rst):
                            request.session['home_page'] = "No Changes dectected"
                            return HttpResponseRedirect(reverse('rst2slides:home_page'))
                        else:
                            slide = Slide.objects.get(slide_name=slide_name)
                            slide.slide_rst = request.GET['myTextBox']
                            slide.slide_last_update = timezone.now()
                            slide.slide_html_content = html_content
                            slide.slide_theme = theme
                            slide.save()
                            return HttpResponseRedirect(reverse('rst2slides:userSlide'))

                slide = Slide(slide_name=slide_name, slide_username=user.username,
                              slide_rst=request.GET['myTextBox'],
                              slide_share_time=timezone.now(), slide_last_update=timezone.now(), slide_rating=0,
                              slide_html_content=html_content, slide_theme=theme)
                slide.save()
                return HttpResponseRedirect(reverse('rst2slides:userSlide'))

        elif submit == 'update':
            old_slide_name = request.session['old_slide_name']
            slide_name = request.GET['slide_name']
            slide = Slide.objects.get(slide_name=old_slide_name, slide_username=user.username)

            list_slide = Slide.objects.filter(
                slide_name=slide_name)  # current user can't create slide is have same name already but another user can create same name

            for checkSlide in list_slide:
                if (slide_name != old_slide_name) and (
                            slide_name == checkSlide.slide_name):  # if change new name and new name have already. it can't create new.
                    request.session['editSlide'] = "New name is has already"
                    return HttpResponseRedirect(reverse('rst2slides:editSlide', kwargs={'slide_name': old_slide_name.replace(" ","_"),
                                                                                        'slide_username': slide.slide_username}))

            if (theme == slide.slide_theme) and (request.GET['myTextBox'] == slide.slide_rst) and (
                        old_slide_name == slide_name):
                request.session['editSlide'] = "No Changes dectected"
                return HttpResponseRedirect(reverse('rst2slides:editSlide', kwargs={'slide_name': slide.slide_name.replace(" ","_"),
                                                                                    'slide_username': slide.slide_username}))
            else:
                slide.slide_rst = request.GET['myTextBox']
                slide.slide_name = slide_name  # change the slide name
                slide.slide_last_update = timezone.now()
                slide.slide_html_content = html_content
                slide.slide_theme = theme
                slide.save()
                return HttpResponseRedirect(reverse('rst2slides:userSlide'))

        elif submit == 'public':
            list_slide = Slide.objects.filter(
                slide_username=user.username)  # current user can't create slide is have same name already but another user can create same name
            slide_name = request.GET['slide_name']
            if not list_slide:
                slide = Slide(slide_name=slide_name, slide_username=user.username, slide_rst=request.GET['myTextBox'],
                              slide_share_time=timezone.now(), slide_last_update=timezone.now(), slide_rating=0,
                              slide_html_content=html_content, slide_theme=theme, slide_is_public=True)
                slide.save()
                return HttpResponseRedirect(reverse('rst2slides:presentationPage'))
            else:
                for slide in list_slide:
                    if slide_name == slide.slide_name:
                        if (theme == slide.slide_theme) and (request.GET['myTextBox'] == slide.slide_rst) and (
                                    slide.slide_is_public == True):
                            request.session['editSlide'] = "No Changes dectected"

rst2slides/templates/rst2slides/contactPage.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Contact Page</title>


    {% load staticfiles%}


    <link rel="stylesheet" type="text/css" href="{% static 'rst2slides/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'rst2slides/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}">

    <script src="{% static 'rst2slides/javascript/angular.min.js' %}"></script>
    <script src="{% static 'rst2slides/javascript/jquery-2.2.3.min.js' %}"></script>
</head>

<body>

<div id='cssmenu'>
    <ul>
        <li><a href="{% url 'rst2slides:home_page' %}">Home</a></li>
        <li><a href="{% url 'rst2slides:presentationPage' %}">Presentation</a></li>
        <li class='active'><a href="{% url 'rst2slides:contactPage' %}">Contact</a></li>

        {% if user.is_authenticated %}
        <li style="float:right;"><a href="{% url 'rst2slides:logoutUser' %}">Log out</a></li>
        <li style="float:right;"><a href="{% url 'rst2slides:userSlide' %}" ">Welcome {{user.username}}</a></li>

        {% else %}
        <li style="float:right;"><a href="{% url 'rst2slides:loginPage' %}">Sign in</a></li>
         {% endif%}
    </ul>
</div>

<div class="container">
    <h1 align="center"><ins>About Developer</ins></h1>
    <br>
    <table>
        <tr>
            <td>
                <image src="{% static 'rst2slides/images/me.jpg' %}" width="400" height="500"></image>
            </td>

            <td valign="top" align="left" style="padding: 30px;">

    <li><h3>Name: Chatchai Honarongsiri</h3></li>
    <li><h3>Nickname: Nuk</h3></li>
    <li><h3>Education’s Background : Studying A King Mongkut's University of Technology North Bangkok</h3></li>
    <li><h3>Major: Computer Engineering</h3></li>
    <li><h3>E-mail: soulquiza@gmail.com</h3></li>

            </td>
        </tr>


    </table>

</div>

</body>
</html>

rst2slides/templates/rst2slides/editSlide.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Slide</title>
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'rst2slides/style.css' %}"/>
    <script src="{% static 'rst2slides/javascript/angular.min.js' %}"></script>
    <script src="{%static 'rst2slides/javascript/home_page.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'rst2slides/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}">

</head>
<body>

<div id='cssmenu'>
    <ul>
        <li><a href="{% url 'rst2slides:home_page' %}">Home</a></li>
        <li class='active'><a href="{% url 'rst2slides:presentationPage' %}">Presentation</a></li>
        <li><a href="{% url 'rst2slides:contactPage' %}">Contact</a></li>

        {% if user.is_authenticated %}
        <li style="float:right;"><a href="{% url 'rst2slides:logoutUser' %}">Log out</a></li>
        <li style="float:right;"><a href="{% url 'rst2slides:userSlide' %}" ">Welcome {{user.username}}</a></li>

        {% else %}
        <li style="float:right;"><a href="{% url 'rst2slides:loginPage' %}">Sign in</a></li>
        {% endif%}
    </ul>
</div>


<div class="container">
    <h1>
        <ins>RST To Presentation</ins>
    </h1>
    <form>


        <h4>Slide's Name:</h4> <input required type="text" value="{{slide.slide_name}}" name="slide_name"
                                          placeholder="Enter name of slides"
                                          class="form-control">

        <br>
        {% if request.session.editSlide %}
        <h4 style="color:red;">{{request.session.editSlide}}</h4>
        {% endif %}
        Text's Color: <!-- <select id="text_colors" >
        <option value="black" selected="selected">Black</option>
        <option value="red">Red</option>
        <option value="blue">Blue</option>
        <option value="green">Green</option>
        <option value="pink">Pink</option>
    </select> -->
        <input type="color" id="text_color" onchange="change_style()" value="#000000">
        Text's font size:<select id="text_size" onclick="change_style()">
        <option value="12px" >12</option>
        <option value="14px" selected="selected">14</option>
        <option value="16px">16</option>
        <option value="18px">18</option>
        <option value="20px">20</option>
        <option value="22px">22</option>
        <option value="24px">24</option>
        <option value="26px">26</option>
        <option value="28px">28</option>
        <option value="30px">30</option>
        <option value="32px">32</option>
        <option value="34px">34</option>
    </select>
        Images :
        <a href="JavaScript:newPopup({% url 'rst2slides:uploadImagePage' %});" class="btn btn-default">Upload</a>
        <br><br>
    <textarea class="form-control" name="myTextBox" cols="100" rows="20" id="text_area"
              style="color:#000000;" placeholder="Enter some ReStructuretext...">{{slide.slide_rst}}</textarea><br>

        <br>
        <h2>Theme : </h2>
        <select name="theme" id="theme" onclick="changeImage()">
            {% for theme in all_theme %}
                {% if last_theme == theme %}
                    <option value="{{last_theme}}" selected="selected">{{last_theme}}</option>
                {% else %}
                    <option value="{{theme}}">{{theme}}</option>
                {% endif %}
            {% endfor %}

        </select><br><br> <img src="/static/rst2slides/images/{{last_theme}}.png" alt="theme" height="500" width="700"
                               id="theme_preview">
        <br>
        <br>

        <div ng-app="previewSlides" ng-controller="previewSlidesController">
            <button name="submit" value="submit" ng-click="showPreview()" formaction="{% url 'rst2slides:rst2html' %}"
                    formtarget="previewSlidesFrame">
                Preview
            </button>

            <button name="submit" value="submit" ng-show="displayStatus" formaction="{% url 'rst2slides:rst2html' %}"
                    formtarget="previewSlidesFrame">
                Refresh
            </button>
            <br><br>
            <iframe ng-show="displayStatus" name="previewSlidesFrame" width="100%" height="500"></iframe>
        </div>
        <!--<input type="image" src="{% static 'rst2slides/images/submit-button.jpg' %}" alt="Submit" width="220"
               height="70" formaction="{% url 'rst2slides:rst2html' %}"> -->
        <button name="submit" value="submit" class="btn-lg btn-primary"
                formaction="{% url 'rst2slides:rst2html' %}">Submit
        </button>
        &nbsp;&nbsp;&nbsp;
        {% if isCanEdit %}
        <button class="btn-lg btn-danger" formaction="{% url 'rst2slides:deleteSlide' %}">Delete</button>
        &nbsp;&nbsp;&nbsp;
        {% if slide.slide_is_public%}
        <button name="submit" value="private" class="btn-lg btn-warning" formaction="{% url 'rst2slides:rst2html' %}">
            Private
        </button>
        &nbsp;&nbsp;&nbsp;
        {% else %}
        <button name="submit" value="editPublic" class="btn-lg btn-info" formaction="{% url 'rst2slides:rst2html' %}">
            Public
        </button>
        &nbsp;&nbsp;&nbsp;
        {% endif%}
        <button name="submit" value="update" class="btn-lg btn-success" formaction="{% url 'rst2slides:rst2html' %}">
            Update
        </button>
        {% endif %}
    </form>

</div>

</body>
</html>

rst2slides/templates/rst2slides/home_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>RST To Presentation Web</title>
    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'rst2slides/style.css' %}"/>
    <script src="{% static 'rst2slides/javascript/angular.min.js' %}"></script>
    <script src="{%static 'rst2slides/javascript/home_page.js' %}" type="text/javascript"></script>
    <link rel="stylesheet" href="{% static 'rst2slides/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}">

</head>
<body>
<div id='cssmenu'>
    <ul>
        <li class='active'><a href="{% url 'rst2slides:home_page' %}">Home</a></li>
        <li><a href="{% url 'rst2slides:presentationPage' %}">Presentation</a></li>
        <li><a href="{% url 'rst2slides:contactPage' %}">Contact</a></li>

        {% if user.is_authenticated %}
        <li style="float:right;"><a href="{% url 'rst2slides:logoutUser' %}">Log out</a></li>
        <li style="float:right;"><a href="{% url 'rst2slides:userSlide' %}" ">Welcome {{user.username}}</a></li>

        {% else %}
        <li style="float:right;"><a href="{% url 'rst2slides:loginPage' %}">Sign in</a></li>
         {% endif%}
    </ul>
</div>


<div class="container">
    <h1>
        <ins>RST To Presentation</ins>
    </h1>
    <form>
        <div ng-app="previewSlides" ng-controller="previewSlidesController">
            {%verbatim%}
        <h4>Slide's Name: {{slide_name}}</span></h4> <input required type="text" ng-model="slide_name" name="slide_name" placeholder="Enter name of slides"
                                      class="form-control"><br>{%endverbatim%}
        {% if request.session.home_page %}
            <h4 style="color:red;">{{request.session.home_page}}</h4>
        {% endif %}
        Text's Color: <!-- <select id="text_colors" >
        <option value="black" selected="selected">Black</option>
        <option value="red">Red</option>
        <option value="blue">Blue</option>
        <option value="green">Green</option>
        <option value="pink">Pink</option>
    </select> -->
        <input type="color" id="text_color" onchange="change_style()" value="#000000">
        Text's font size:<select id="text_size" onclick="change_style()">
        <option value="12px" >12</option>
        <option value="14px" selected="selected">14</option>
        <option value="16px">16</option>
        <option value="18px">18</option>
        <option value="20px">20</option>
        <option value="22px">22</option>
        <option value="24px">24</option>
        <option value="26px">26</option>
        <option value="28px">28</option>
        <option value="30px">30</option>
        <option value="32px">32</option>
        <option value="34px">34</option>
    </select>
        Images :
        <a href="JavaScript:newPopup({% url 'rst2slides:uploadImagePage' %});" class="btn btn-default">Upload</a>
        <br><br>
    <textarea class="form-control" name="myTextBox" cols="100" rows="20" id="text_area"
              style="color:#000000;" placeholder="Enter some ReStructuretext..."></textarea><br>

        <br>
        <h2>Theme : </h2>
        <select name="theme" id="theme" onclick="changeImage()">
            <option value="deck" selected="selected">deck</option>
            <option value="clean">clean</option>
            <option value="reveal">reveal</option>
            <option value="bootstrap">bootstrap</option>
        </select><br><br> <img src="{% static 'rst2slides/images/deck.png' %}" alt="theme" height="500" width="700"
                               id="theme_preview">
        <br>
        <br>


            <button name="submit" value="submit" ng-click="showPreview()" formaction="{% url 'rst2slides:rst2html' %}"
                    formtarget="previewSlidesFrame">
                Preview
            </button>

            <button name="submit" value="submit" ng-show="displayStatus" formaction="{% url 'rst2slides:rst2html' %}"
                    formtarget="previewSlidesFrame">
                Refresh
            </button>
            <br><br>
            <iframe ng-show="displayStatus" name="previewSlidesFrame" width="100%" height="500"></iframe>
        </div>
        <!--<input type="image" src="{% static 'rst2slides/images/submit-button.jpg' %}" alt="Submit" width="220"
               height="70" formaction="{% url 'rst2slides:rst2html' %}"> -->
        <button name="submit" value="submit" class="btn-lg btn-primary" formaction="{% url 'rst2slides:rst2html' %}">Submit</button>
        {% if user.is_authenticated %}
        <button name="submit" value="save" class="btn-lg btn-success" formaction="{% url 'rst2slides:rst2html' %}">Save</button>
        <button name="submit" value="public" class="btn-lg btn-info" formaction="{% url 'rst2slides:rst2html' %}">Public</button>
        {% endif %}
    </form>

</div>

</body>
</html>

rst2slides/templates/rst2slides/imageCodeRst.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Image Code Rst</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'rst2slides/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'rst2slides/style.css' %}"/>
    <script src="{% static 'rst2slides/javascript/angular.min.js' %}"></script>
    <script src="{%static 'rst2slides/javascript/home_page.js' %}" type="text/javascript"></script>
</head>
<body>
<div class="container">
    <h3>Copy and Paste it at Text area : </h3><input type="text" class="form-control"
                                                     value=".. image:: /static/rst2slides/images/user/{{request.session.imageName}}"
                                                     readonly>
    <br>
    <image src="/static/rst2slides/images/user/{{request.session.imageName}}" style="width:100%;height:100%;"></image>
</div>

</body>
</html>

rst2slides/templates/rst2slides/loginPage.html
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>Login Page</title>


        {% load staticfiles%}

        <link rel="stylesheet" href="{% static 'rst2slides/css/loginPage.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'rst2slides/style.css' %}"/>
        <script src="{% static 'rst2slides/javascript/angular.min.js' %}"></script>
        <link rel="stylesheet" href="{% static 'rst2slides/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}">

  </head>

  <body>

    <div id='cssmenu'>
    <ul>
        <li ><a href="{% url 'rst2slides:home_page' %}">Home</a></li>
        <li><a href="{% url 'rst2slides:presentationPage' %}">Presentation</a></li>
        <li><a href="{% url 'rst2slides:contactPage' %}">Contact</a></li>

        <li class='active' style="float:right;"><a href="{% url 'rst2slides:loginPage' %}">Sign in</a></li>

    </ul>
</div>



    <div class="login-page">
  <div class="form">
    <form class="register-form" method="post">
        {% csrf_token %}
      <input required name="register name" type="text" placeholder="name"/>
      <input required name="register password" type="password" placeholder="password"/>
      <input required name="register email address" type="text" placeholder="email address"/>
      <button formaction="{% url 'rst2slides:registerUser' %}">create</button>
      <p class="message">Already registered? <a href="#">Sign In</a></p>
    </form>
    <form class="login-form" method="post">
        {% csrf_token%}
      <input required name="username" type="text" placeholder="username"/>
      <input required name="userpassword" type="password" placeholder="password"/>
      <button formaction="{% url 'rst2slides:loginUser' %}">login</button>
      <p class="message">Not registered? <a href="#">Create an account</a></p>
    </form>
      <h3 align="center" style="color:red;">{{request.session.loginPage}}</h3>
      <h3 align="center" style="color:green;">{{request.session.loginPageSuccess}}</h3>
  </div>
</div>
    <script src="{% static 'rst2slides/javascript/jquery-2.2.3.min.js' %}"></script>

        <script src="{% static 'rst2slides/javascript/loginPage.js' %}"></script>




  </body>
</html>

rst2slides/templates/rst2slides/uploadImagePage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload Image Page</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'rst2slides/bootstrap-3.3.6-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'rst2slides/style.css' %}"/>
    <script src="{% static 'rst2slides/javascript/angular.min.js' %}"></script>
    <script src="{%static 'rst2slides/javascript/home_page.js' %}" type="text/javascript"></script>
</head>
<body>
<div class="container">
    <h1>
        <ins>Upload Image Page</ins>
    </h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="pic" accept="image/*"><br>
        <button class="btn btn-primary btn-block" formaction="{% url 'rst2slides:uploadImage' %}">Upload Image</button>
    </form>

</div>
</body>
</html>